server:
   port: 8080

spring:
  application:
     name: facturacion
  datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: ${AIVEN_MYSQL_URL}
     username: ${AIVEN_MYSQL_USERNAME}
     password: ${AIVEN_MYSQL_PASSWORD}
  jpa:
     hibernate:
        ddl-auto: update
     database: mysql
     database-platform: org.hibernate.dialect.MySQLDialect
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: 86400000
      refresh-token:
        expiration: 604800000
logging:
  pattern:
    console: "%d{HH:mm:ss} %-5level [%logger{36}] - %msg%n"
  level:
    com.nimbusds: TRACE
    org.springframework.security.oauth2.jwt: TRACE
    org.springframework.security.oauth2: TRACE
    org.springframework.security: DEBUG